Assignment2/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment2.Data;
using Assignment2.Models;

namespace Assignment2.Controllers
{
    public class CategoriesController : Controller
    {
        private Assignment2Context db = new Assignment2Context();

        // GET: Categories
        public ActionResult Index()
        {
            //return View(db.Categories.ToList());
            return View(db.Categories.OrderBy(c => c.Name).ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            foreach (var p in category.Products)
            {
                p.CategoryID = null;
            }
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment2.Data;
using Assignment2.Models;
using static Assignment2.Models.ProductIndexViewModel;
using PagedList;

namespace Assignment2.Controllers
{
    public class ProductsController : Controller
    {
        private Assignment2Context db = new Assignment2Context();

        public ActionResult Index(string category, string search, int? page, String sortBy)
        {

            //instantiate a new view model
            ProductIndexViewModel viewModel = new ProductIndexViewModel();
            var products = db.Products.Include(p => p.Category);
            //perform the search and save the search string to the viewModel
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.Name.Contains(search) ||
                p.Description.Contains(search) ||
               p.Category.Name.Contains(search));
                viewModel.Search = search;
            }

            viewModel.CatsWithCount = from matchingProducts in products
                                      where matchingProducts.CategoryID != null
                                      group matchingProducts by
                                      matchingProducts.Category.Name into
                                       catGroup
                                      select new CategoryWithCount()
                                      {
                                          CategoryName = catGroup.Key,
                                          ProductCount = catGroup.Count()
                                      };
            if (!String.IsNullOrEmpty(category))
            {
                products = products.Where(p => p.Category.Name == category);
                viewModel.Category = category;
            }
            switch (sortBy)
            {
                case "price_lowest":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "price_highest":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderBy(p => p.Name);
                    break;
            }
            //viewModel.Products = products; 
            viewModel.SortBy = sortBy;
            viewModel.Sorts = new Dictionary<string, string>
{
{"Release date early to late", "price_lowest" },
{"Release date late to early", "price_highest" }
};
            const int PageItems = 3;
            int currentPage = (page ?? 1);
            viewModel.Products = products.ToPagedList(currentPage, PageItems);
            return View(viewModel);
        }




        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // POST: Products/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price,Description,CategoryID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // POST: Products/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price,Description,CategoryID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/MyJavaScript.js"></script>
    <script src="~/Scripts/check.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm" style="background-image: url('/Content/Picture/导航栏.png') ;">
        <div class="container">
            <div id="Farewell">
                @Html.ActionLink("Farewell My Concubine |  ", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
            </div>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="切换导航" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("ABOUT", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("DETAILS", "Details", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @*<li>@Html.ActionLink("PHOTOS AND MUSIC", "Photos", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                    <li>@Html.ActionLink("PHOTOS AND MUSIC", "Index", "Categories", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("MORE INFORMATION", "Index", "Products", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("CONTACT", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <div class="search-title">
                    @using (Html.BeginForm("Index", "Products", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
                    {
                        <div class="form-group">
                            @Html.TextBox("Search", null, new { @class = "form-control", @placeHolder = "Srearch Products" })
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    }
                </div>
            </div>
        </div>
    </nav>

    <img src="~/Content/Picture/HOME.png" alt="mainPicture" />
    <div class="containers">
        @RenderBody()
        <footer>
            <div class="container-4">
                <div class="column1">
                    <h3>Company</h3>
                    <p>Hrbut,Hongqiao District,Tianjin City,300000</p>
                    <ul>
                        <li>
                            <a href="tel:+18033702637">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16" color=#f89d35>
                                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                                </svg>
                                "18033702637"
                            </a>
                        </li>
                        <li>
                            <a href="mailto:sgreer@example.com/harpe">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16" color=#f89d35>
                                    <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z" />
                                </svg>
                                "695628449@qq.com"
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="column2">
                    <h3>Quick Links</h3>
                    <ul>
                        <li>@Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("ABOUT", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("DETAILS", "Details", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("PHOTOS AND MUSIC", "Index", "Categories", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("MORE INFORMATION", "Index", "Products", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("CONTACT", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>

                </div>
                <div class="column3">
                    <h3>Subscribe Us</h3>
                    <p>Subscribe to get latest news article and resources</p>
                    <from actions="#">
                        <input type="text" class="input-text" id="content" placeholder="Subscribe Now..." />
                        <input type="button" class="button" onclick="myFunction()" value="Subscribe" />
                    </from>
                    <h3>Validator Detection</h3>
                    <ul>
                        <li><a href="https://validator.w3.org/docs/users.html#Calling" onclick="validateHTML()" target="_blank">W3C Validator API</a></li>
                        <li><a href="https://jigsaw.w3.org/css-validator/manual.html" onclick="validateCSS()" target="_blank">CSS Validator</a></li>
                    </ul>
                </div>
                <div class="column4">
                    <h3>Gallery</h3>
                    <div class="gallery">
                        <img src="~/Content/Picture/footer1.jpg" alt="footer1">
                        <img src="~/Content/Picture/footer2.jpg" alt="footer2">
                        <img src="~/Content/Picture/footer3.jpg" alt="footer3">
                        <img src="~/Content/Picture/footer4.jpg" alt="footer4">
                        <img src="~/Content/Picture/footer5.jpg" alt="footer5">
                        <img src="~/Content/Picture/footer6.jpg" alt="footer6">
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html >